AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
